name: Slack Notification on Failure

on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    # slack notification
    steps:
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_USERNAME: rtBot (GitHub Actions)
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_TITLE: masterに反映されました🎉
        SLACK_COLOR: good
        SLACK_MESSAGE: ${{ github.event.repository.url }}
        MSG_MINIMAL: true
